export const REPLIES_LIST_REQUEST = 'REPLIES_LIST_REQUEST';
export const REPLIES_LIST_SUCCESS = 'REPLIES_LIST_SUCCESS';
export const REPLIES_LIST_FAIL = 'REPLIES_LIST_FAIL';

export const REPLIES_SET_POST_ID = 'REPLIES_SET_POST_ID';
