export const COMMENTS_LIST_REQUEST = 'COMMENTS_LIST_REQUEST';
export const COMMENTS_LIST_SUCCESS = 'COMMENTS_LIST_SUCCESS';
export const COMMENTS_LIST_FAIL = 'COMMENTS_LIST_FAIL';

export const COMMENTS_SET_ACTIVE_POST_ID = 'COMMENTS_SET_ACTIVE_POST_ID';
